load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("//scripts:cgo_test.bzl", "go_cgo_test")

go_library(
    name = "handler",
    srcs = [
        "chat.go",
        "cache_identity.go",
        "cache_lineage.go",
        "chat_messages.go",
        "chat_response.go",
        "chat_stream.go",
        "chat_token.go",
        "completion.go",
        "logits.go",
        "model.go",
    ],
    importpath = "github.com/qualcomm/GenieX/cli/server/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//bindings/go:geniex_sdk_go",
        "//cli/internal/config",
        "//cli/internal/thinkfsm",
        "//cli/server/service",
        "//cli/server/types",
        "//cli/server/utils",
        "@com_github_bytedance_sonic//:sonic",
        "@com_github_gin_gonic_gin//:gin",
        "@com_github_openai_openai_go_v3//:openai-go",
        "@com_github_openai_openai_go_v3//packages/param",
        "@com_github_openai_openai_go_v3//shared/constant",
    ],
)

go_cgo_test(
    name = "handler_test",
    srcs = [
        "chat_messages_test.go",
        "chat_response_test.go",
        "chat_stream_test.go",
        "chat_test.go",
        "cache_identity_test.go",
        "cache_lineage_test.go",
        "completion_test.go",
    ],
    embed = [":handler"],
)
